name: Build Kernel
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  CONFIG: "config.json"
  OUTPUT_DIR: "out"

jobs:
  read_config:
    runs-on: ubuntu-latest
    outputs:
      matrix_tools_preset: ${{ steps.config.outputs.matrix_tools_preset }}
      run_build: ${{ steps.config.outputs.run_build }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up jq"
        run: sudo apt-get install -y jq

      - name: "Read config -- 读取配置"
        id: config
        run: |
          CONFIG_FILE="$GITHUB_WORKSPACE/$CONFIG"
      
          USE_PRESET=$(jq -r '.tools_config.use_preset' $CONFIG_FILE)
          USE_MATRIX=$(jq -r '.tools_config.use_matrix' $CONFIG_FILE)
          CUSTOM=$(jq -r '.tools_config.custom' $CONFIG_FILE)
      
          set_tools_env_vars() {
            local tools_json=$1
            for tool in $(jq -c 'to_entries[]' <<< "$tools_json"); do
              local tool_name=$(jq -r '.key' <<< "$tool")
              local tool_version=$(jq -r '.value' <<< "$tool")
              echo "${tool_name}_VERSION=$tool_version" >> $GITHUB_ENV
            done
          }
      
          if [[ "$CUSTOM" == "true" ]]; then
            echo "custom=true"
            my_custom_tools=$(jq -c '.my_custom_tools' $CONFIG_FILE)
            echo "my_custom_tools=$my_custom_tools" >> $GITHUB_OUTPUT
            echo "run_build=true" >> $GITHUB_OUTPUT
            set_tools_env_vars "$my_custom_tools"
      
          elif [[ "$USE_MATRIX" == "true" && "$CUSTOM" == "false" ]]; then
            echo "use_matrix=true"
            tools_preset=$(jq -c '.tools_preset' $CONFIG_FILE)
            echo "matrix_tools_preset=$(echo $tools_preset | jq -c .)" >> $GITHUB_OUTPUT
            echo "run_build=true" >> $GITHUB_OUTPUT
      
          elif [[ "$USE_MATRIX" == "false" && "$CUSTOM" == "false" ]]; then
            echo "use_preset=true"
            tools_preset=$(jq -c --arg preset "$USE_PRESET" '.tools_preset[$preset]' $CONFIG_FILE)
            echo "matrix_tools_preset=$(echo $tools_preset | jq -c .)" >> $GITHUB_OUTPUT
            echo "run_build=true" >> $GITHUB_OUTPUT
            set_tools_env_vars "$tools_preset"
      
          else
            echo "run_build=false" >> $GITHUB_OUTPUT
            echo "未匹配到任何构建条件，跳过构建。"
          fi

      - name: "Debug outputs"
        run: |
          echo "Matrix Tools Preset: ${{ steps.config.outputs.matrix_tools_preset }}"
          echo "Run Build: ${{ steps.config.outputs.run_build }}"

  build:
    name: "Build Kernel"
    runs-on: ubuntu-latest
    needs: read_config
    if: ${{ needs.read_config.outputs.run_build == 'true' }}
    strategy:
      matrix:
        tools: ${{ fromJson(needs.read_config.outputs.matrix_tools_preset) }}
      fail-fast: false
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: "Set up jq"
        run: sudo apt-get install -y jq

      - name: "Cache dependencies"
        uses: actions/cache@v4
        with:
          path: /usr/local/bin
          key: ${{ runner.os }}-gcc-${{ matrix.tools.aarch64-linux-android- }}-clang-${{ matrix.tools.clang }}-ld-${{ matrix.tools.ld }}-make-${{ matrix.tools.make }}-objcopy-${{ matrix.tools.objcopy }}-objdump-${{ matrix.tools.objdump }}-strip-${{ matrix.tools.strip }}
          restore-keys: |
            ${{ runner.os }}-gcc-${{ matrix.tools.aarch64-linux-android- }}-clang-${{ matrix.tools.clang }}-ld-${{ matrix.tools.ld }}-make-${{ matrix.tools.make }}-objcopy-${{ matrix.tools.objcopy }}-objdump-${{ matrix.tools.objdump }}-strip-${{ matrix.tools.strip }}

      - name: "Download tools -- 下载编译工具"
        run: |
          echo "下载编译工具"
          echo "更新完成"
          echo "安装特定版本的编译工具"

      - name: "Build Kernel"
        run: |
          echo "构建内核"
          # 在此处添加内核构建命令