name: Build Kernel
on:
  workflow_dispatch:
env:
  CONFIG: "config.json"
  OUTPUT_DIR: "out" # 输出文件位置

  
#######################################################################################


jobs:
  set_up:
    name: "set_env -- 设置环境变量"
    runs-on: ubuntu-latest
    steps:

    
    

  Get_ready:
    name: "Get_tools -- 获取编译工具"
    runs-on: ubuntu-latest
    
  
    


  build:
    name: "作者:${{ github.actor }} -- building - - - - - - - - - - - -"
    runs-on: ubuntu-latest 
    
