name: Build Android Kernel

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [gcc, clang]  # 工具组合
        variant: [gki, vanilla]   # 内核变体
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Toolchain
        run: |
          if [ "${{ matrix.toolchain }}" == "gcc" ]; then
            sudo apt-get install gcc-arm-linux-gnueabi
          else
            sudo apt-get install clang
          fi

      - name: Configure Kernel
        run: |
          cd kernel  # 进入内核源代码目录
          if [ "${{ matrix.variant }}" == "gki" ]; then
            make gki_defconfig
          else
            make vanilla_defconfig
          fi

      - name: Compile Kernel
        run: |
          make -j$(nproc) ARCH=arm CROSS_COMPILE=$(if [ "${{ matrix.toolchain }}" == "gcc" ]; then echo "arm-linux-gnueabi-"; else echo "aarch64-linux-gnu-"; fi)
