name: Build Kernel

on:
  workflow_dispatch:

jobs:
  set_up:
    runs-on: ubuntu-latest
    steps:
      - name: Set Environment Variables
        run: |
          echo "Setting up environment variables"

  Get_ready:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set Up Toolchain
        run: |
          sudo apt-get update
          sudo apt-get install gcc-arm-linux-gnueabi clang

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [gcc, clang]
        variant: [gki, vanilla]
    needs: Get_ready
    steps:
      - name: Compile Kernel
        run: |
          cd kernel
          if [ "${{ matrix.variant }}" == "gki" ]; then
            make gki_defconfig
          else
            make vanilla_defconfig
          fi
          make -j$(nproc) ARCH=arm CROSS_COMPILE=$(if [ "${{ matrix.toolchain }}" == "gcc" ]; then echo "arm-linux-gnueabi-"; else echo "aarch64-linux-gnu-"; fi)